### ISSUE TITLE
CustomNamingStrategy

### ISSUE THREAD

**Issue by Greibit** [RobinCK/typeorm-fixtures-sample#1]
Hi!

I'm using a custom naming strategy to generate my database schema, but when I run fixtures command, it doesn't use this custom naming strategy.

In my AppModule I have this code to load the CustomNamingStrategy:
`
getConnectionOptions().then(connectionOptions => {
    return createConnection(Object.assign(connectionOptions, {
        namingStrategy: new SnakeNamingStrategy(),
    }));
});
`

How can I configure fixtures command to use the same custom naming strategy?

**Comment by RobinCK** [comment]
Maybe you will help https://github.com/RobinCK/typeorm-fixtures/issues/5

**Comment by Greibit** [comment]
Changing my ormconfig.json to ormconfig.ts like https://github.com/RobinCK/typeorm-fixtures/issues/5 works
